variable "region_name" {}
variable "vpc_cidr_block" {}
variable "vpc_tags" {}
variable "subnet_cidr" {}
variable "private_cidr" {}
variable "route_cidr" {}
variable "igw_tag" {}
variable "subnet_tag" {}
variable "route_table_tag" {}
variable "security_cidr" {}
variable "security_group_name" {}
variable "instance_type" {}
variable "azs" {}